menus = [
    {
        "name": "Espresso",
        "desc": "A concentrated coffee beverage brewed by forcing pressurized water through finely ground coffee.",
        "price": 25000,
        "img_url": "https://example.com/espresso.jpg",
        "stock": 20,
        "category": "drinks",
    },
    {
        "name": "Cappuccino",
        "desc": "A coffee-based drink made with espresso, hot milk, and steamed milk foam.",
        "price": 35000,
        "img_url": "https://example.com/cappuccino.jpg",
        "stock": 15,
        "category": "drinks",
    },
    {
        "name": "Latte",
        "desc": "A coffee-based drink made with espresso and steamed milk, topped with milk foam.",
        "price": 40000,
        "img_url": "https://example.com/latte.jpg",
        "stock": 18,
        "category": "drinks",
    },
    {
        "name": "Mocha",
        "desc": "A variant of a latte with added chocolate flavor, often topped with whipped cream.",
        "price": 45000,
        "img_url": "https://example.com/mocha.jpg",
        "stock": 12,
        "category": "drinks",
    },
    {
        "name": "Iced Coffee",
        "desc": "Chilled coffee served over ice, often with added milk and sweetener.",
        "price": 30000,
        "img_url": "https://example.com/iced_coffee.jpg",
        "stock": 25,
        "category": "drinks",
    },
    {
        "name": "Americano",
        "desc": "A single shot of espresso diluted with hot water, similar to black coffee.",
        "price": 28000,
        "img_url": "https://example.com/americano.jpg",
        "stock": 22,
        "category": "drinks",
    },
    {
        "name": "Croissant",
        "desc": "A buttery, flaky pastry often enjoyed with coffee.",
        "price": 20000,
        "img_url": "https://example.com/croissant.jpg",
        "stock": 30,
        "category": "foods",
    },
    {
        "name": "Muffin",
        "desc": "A sweet or savory individual-sized quick bread often enjoyed with coffee.",
        "price": 18000,
        "img_url": "https://example.com/muffin.jpg",
        "stock": 28,
        "category": "foods",
    },
    {
        "name": "Bagel",
        "desc": "A ring-shaped bread roll, typically sliced and toasted, often served with spreads or fillings.",
        "price": 22000,
        "img_url": "https://example.com/bagel.jpg",
        "stock": 24,
        "category": "foods",
    },
    {
        "name": "Quiche",
        "desc": "A savory tart with a crust made of pastry dough filled with a mixture of eggs, milk or cream, and various ingredients.",
        "price": 32000,
        "img_url": "https://example.com/quiche.jpg",
        "stock": 14,
        "category": "foods",
    },
    {
        "name": "Flat White",
        "desc": "A coffee beverage made with a double shot of espresso and steamed milk, topped with a thin layer of velvety microfoam.",
        "price": 38000,
        "img_url": "https://example.com/flat_white.jpg",
        "stock": 18,
        "category": "drinks",
    },
    {
        "name": "Macchiato",
        "desc": "A shot of espresso with a small amount of milk, usually served with a dollop of foam.",
        "price": 32000,
        "img_url": "https://example.com/macchiato.jpg",
        "stock": 15,
        "category": "drinks",
    },
    {
        "name": "Iced Mocha",
        "desc": "A refreshing combination of espresso, chocolate syrup, cold milk, and ice, often topped with whipped cream.",
        "price": 45000,
        "img_url": "https://example.com/iced_mocha.jpg",
        "stock": 12,
        "category": "drinks",
    },
    {
        "name": "Affogato",
        "desc": "A dessert consisting of a scoop of vanilla ice cream or gelato 'drowned' with a shot of hot espresso.",
        "price": 40000,
        "img_url": "https://example.com/affogato.jpg",
        "stock": 10,
        "category": "drinks",
    },
    {
        "name": "Iced Tea",
        "desc": "A refreshing beverage made with brewed tea, served chilled and often flavored with fruits or herbs.",
        "price": 30000,
        "img_url": "https://example.com/iced_tea.jpg",
        "stock": 25,
        "category": "drinks",
    },
    {
        "name": "Croissant Sandwich",
        "desc": "A delicious croissant filled with ham, cheese, and fresh vegetables, served warm.",
        "price": 28000,
        "img_url": "https://example.com/croissant_sandwich.jpg",
        "stock": 20,
        "category": "foods",
    },
    {
        "name": "Scone",
        "desc": "A baked pastry typically made of wheat, sugar, and butter, often flavored with fruits or spices.",
        "price": 18000,
        "img_url": "https://example.com/scone.jpg",
        "stock": 30,
        "category": "foods",
    },
    {
        "name": "Pancakes",
        "desc": "A stack of fluffy pancakes served with maple syrup and a side of fresh fruits.",
        "price": 35000,
        "img_url": "https://example.com/pancakes.jpg",
        "stock": 15,
        "category": "foods",
    },
    {
        "name": "Baguette Sandwich",
        "desc": "A traditional French baguette filled with a variety of ingredients, such as cheese, ham, and vegetables.",
        "price": 42000,
        "img_url": "https://example.com/baguette_sandwich.jpg",
        "stock": 22,
        "category": "foods",
    },
    {
        "name": "Fruit Parfait",
        "desc": "Layers of fresh fruits, yogurt, and granola, served in a glass or bowl.",
        "price": 28000,
        "img_url": "https://example.com/fruit_parfait.jpg",
        "stock": 18,
        "category": "foods",
    },
    {
        "name": "Pour Over",
        "description": "A manual coffee brewing method where hot water is poured over ground coffee in a filter, resulting in a clean and flavorful cup.",
        "price": 35000,
        "image_url": "https://example.com/pour_over.jpg",
        "stock": 20,
        "category": "drinks",
    },
    {
        "name": "Turkish Coffee",
        "description": "A strong coffee prepared by simmering finely ground coffee beans in a special pot called a cezve, often served with a side of Turkish delight.",
        "price": 40000,
        "image_url": "https://example.com/turkish_coffee.jpg",
        "stock": 15,
        "category": "drinks",
    },
    {
        "name": "Vietnamese Iced Coffee",
        "description": "Also known as Ca Phe Da, this coffee is made with dark roast coffee, sweetened condensed milk, and served over ice.",
        "price": 45000,
        "image_url": "https://example.com/vietnamese_iced_coffee.jpg",
        "stock": 12,
        "category": "drinks",
    },
    {
        "name": "Caramel Macchiato",
        "description": "A delicious combination of espresso, steamed milk, vanilla syrup, and caramel sauce, topped with foam and drizzled caramel.",
        "price": 38000,
        "image_url": "https://example.com/caramel_macchiato.jpg",
        "stock": 18,
        "category": "drinks",
    },
    {
        "name": "Iced Matcha Latte",
        "description": "A refreshing and creamy drink made with powdered green tea, milk, and sweetener, served over ice.",
        "price": 42000,
        "image_url": "https://example.com/iced_matcha_latte.jpg",
        "stock": 16,
        "category": "drinks",
    },
    {
        "name": "Batagor",
        "description": "Short for Bakso Tahu Goreng, batagor is a popular Bandung street food consisting of fried fish dumplings and tofu, served with a peanut sauce.",
        "price": 35000,
        "image_url": "https://example.com/batagor.jpg",
        "stock": 18,
        "category": "foods",
    },
    {
        "name": "Cireng",
        "description": "A beloved Bandung snack, cireng is a deep-fried tapioca-based snack served with a chili dipping sauce.",
        "price": 25000,
        "image_url": "https://example.com/cireng.jpg",
        "stock": 25,
        "category": "foods",
    },
    {
        "name": "Pisang Molen",
        "description": "Pisang Molen is a popular snack in Bandung made from crispy pastry filled with sweetened banana filling. It's a delightful combination of crunchy and sweet flavors.",
        "price": 25000,
        "image_url": "https://example.com/pisang_molen.jpg",
        "stock": 25,
        "category": "foods",
    },
    {
        "name": "Cilok Bandung",
        "description": "Cilok is a beloved Bandung street snack made from tapioca flour. These chewy balls are often served with a spicy peanut sauce, resulting in a delightful combination of textures and flavors.",
        "price": 18000,
        "image_url": "https://example.com/cilok_bandung.jpg",
        "stock": 30,
        "category": "foods",
    },
    {
        "name": "Baso Tahu Goreng",
        "description": "Baso Tahu Goreng is a popular Bandung snack consisting of deep-fried tofu filled with a mixture of meatball (baso) and vegetables. It is commonly enjoyed with a tangy and savory sauce.",
        "price": 30000,
        "image_url": "https://example.com/baso_tahu_goreng.jpg",
        "stock": 20,
        "category": "foods",
    },
    ## new menu
    {
        "name": "Cascara Latte",
        "desc": "Unique latte with fruity and floral flavors.",
        "price": 42000,
        "img_url": "https://example.com/cascara_latte.jpg",
        "stock": 20,
        "category": "drinks",
    },
    {
        "name": "Vietnamese Iced Coffee",
        "desc": "Strong and sweet coffee with condensed milk.",
        "price": 38000,
        "img_url": "https://example.com/vietnamese_iced_coffee.jpg",
        "stock": 18,
        "category": "drinks",
    },
    {
        "name": "Ethiopian Yirgacheffe",
        "desc": "Single-origin coffee with floral and citrus notes.",
        "price": 45000,
        "img_url": "https://example.com/ethiopian_yirgacheffe.jpg",
        "stock": 15,
        "category": "drinks",
    },
    {
        "name": "Honduran Marcala",
        "desc": "Medium-bodied coffee with nutty and chocolatey flavors.",
        "price": 40000,
        "img_url": "https://example.com/honduran_marcala.jpg",
        "stock": 12,
        "category": "drinks",
    },
    {
        "name": "Mexican Chiapas",
        "desc": "Smooth and balanced coffee with caramel and citrus hints.",
        "price": 38000,
        "img_url": "https://example.com/mexican_chiapas.jpg",
        "stock": 20,
        "category": "drinks",
    },
    {
        "name": "Guatemalan Antigua",
        "desc": "Rich coffee with dark chocolate flavors and a smoky finish.",
        "price": 42000,
        "img_url": "https://example.com/guatemalan_antigua.jpg",
        "stock": 18,
        "category": "drinks",
    },
    {
        "name": "Costa Rican Tarrazu",
        "desc": "Bright coffee with citrus acidity and notes of caramel.",
        "price": 45000,
        "img_url": "https://example.com/costa_rican_tarrazu.jpg",
        "stock": 15,
        "category": "drinks",
    },
    {
        "name": "Panamanian Geisha",
        "desc": "Highly sought-after coffee with floral and tea-like flavors.",
        "price": 50000,
        "img_url": "https://example.com/panamanian_geisha.jpg",
        "stock": 10,
        "category": "drinks",
    },
    {
        "name": "Nicaraguan Jinotega",
        "desc": "Well-balanced coffee with chocolate and roasted nut flavors.",
        "price": 42000,
        "img_url": "https://example.com/nicaraguan_jinotega.jpg",
        "stock": 18,
        "category": "drinks",
    },
    {
        "name": "Colombian Supremo",
        "desc": "Classic medium-dark roast coffee with a smooth flavor.",
        "price": 38000,
        "img_url": "https://example.com/colombian_supremo.jpg",
        "stock": 20,
        "category": "drinks",
    },
]
