"""add member_name col in balance_record

Revision ID: 6b36d0074227
Revises: 6350cb08945a
Create Date: 2023-06-24 08:48:48.018307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b36d0074227'
down_revision = '6350cb08945a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_name', sa.String(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('paid_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('balance_record', schema=None) as batch_op:
        batch_op.drop_column('member_name')

    # ### end Alembic commands ###
