"""varchar for customer name in Order

Revision ID: 891d3ecbbbc5
Revises: 52dfd4630041
Create Date: 2023-06-22 15:57:10.476196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891d3ecbbbc5'
down_revision = '52dfd4630041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('customer_name',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('total_bill',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('total_bill',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
