"""add cancelled_date in order

Revision ID: 9cfc4dd4854d
Revises: 565fd390ff35
Create Date: 2023-06-22 22:32:42.016726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfc4dd4854d'
down_revision = '565fd390ff35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('cancelled_date')

    # ### end Alembic commands ###
