"""member_name balance record nullable False

Revision ID: b6a4a9a7ed22
Revises: 6b36d0074227
Create Date: 2023-06-24 16:04:45.541756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a4a9a7ed22'
down_revision = '6b36d0074227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_record', schema=None) as batch_op:
        batch_op.alter_column('member_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_record', schema=None) as batch_op:
        batch_op.alter_column('member_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
