"""add completed_date balance

Revision ID: bc0f346e3a5b
Revises: 891d3ecbbbc5
Create Date: 2023-06-22 21:34:55.325388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0f346e3a5b'
down_revision = '891d3ecbbbc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_record', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('completed_date')

    # ### end Alembic commands ###
