"""add cart column in user

Revision ID: da989ea91351
Revises: b6a4a9a7ed22
Create Date: 2023-08-05 01:11:49.855070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da989ea91351'
down_revision = 'b6a4a9a7ed22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cart')

    # ### end Alembic commands ###
